<?php

/**
 * Implements hook_theme().
 */
function current_timezone_theme($existing, $type, $theme, $path) {
    return array('current_timezone' =>                  // this is the name of the template
             array(
              'variables' => array(
                  'country' => null,
                  'city' => null,
                  'timezone' => null
              ),
          )
      );
  }

?>